lc0_main.go
- Wait for selfplay training to finish before removing the
training directory.
- Print the value of Cmd.Wait(), the return value is the errcode
from the subprocess not an error from the wait call, log.Fatal was
wrong here.
- Add Cmd.Wait() calls for the subprocesses in match mode so we
don't leave defunct processes lingering.
- Remove the bestmove print it is very noisy.
=> Several bug fixes:

lc0_main.go
This stripped off server supplied params so we could test against
the prod server and we shouldn't need to run against prod server
now that testserver is fully baked.
=> Remove validateParams.

lc0_main.go
Two small improvements:
1) Treat train exiting without even a single game of progress to be an error, thus ensuring it gets a 30 second wait before retry, so direct loop can be no faster than one every game.
2) Avoid potentially spawning an unlimited number of anonymous functions which poll the server to see if sha or mode have changed by changing the closure check condition once training exits. Otherwise this could be a problem if the client self-exits repeatedly.
=> Add protection against spamming NextGame calls to the server.

lc0_main.go
This was discussed with @Tilps on discord to verify that the client was built with a recent version of github.com/Tilps/chess package.
=> Check e.p. fix to verify recent github.com/Tilps/chess package

lc0_main.go
The parsing was done splitting the string on spaces, which obviously failed if there were spaces in the filename. However we know that the path is between "trainingfile" and "gameid" and the moves are after "moves" so is easy to get those parts. Fixes #9.
=> Fix parsing of gameready

lc0_main.go
Disabled the --gpu option that does nothing, changed the --lc0args example to one working after the new restrictions and a spelling fix.
=> Small cosmetic changes

lc0_main.go
Hopefully this is more reliable at showing lc0 errors when it crashes.
=> Redirect engine stderr to client stdout rather than trying to scan it.

lc0_main.go
Adds the cudnn-fp16 and multiplexing backends and the --parallelism option to the lc0args whitelist.
Also gives a better lc0args example with the --help option.
=> -lc0args handling

lc0_main.go
What is this patch does (as discussed in #29) :
1.  --lc0args is hidden from the help text. (Was harder than I thought it would/should be).
2. New option --backend-opts is used and passed to lc0 with a blacklist check for specific tokens. Currently only "random" is rejected.
3. No checking of --lc0args but a warning is printed that it is intended for testing and "TESTING" is printed in front of all client log output.
4. Server controlled parameters are passed last to lc0 to override user specified ones.
5. New option parallelism is introduced and passed to lc0 for selfplay games.
Currently used commands will continue to work since -lc0args is still available.
=> Better handling of passing arguments to lc0.

README.md, appveyor.yml, lc0_main.go, src/client/client_http.go
This PR extends that of #43 
This PR:
- checks if the downloaded network is a valid gzip
- uses lockfile to ensure that only one client is downloading at any time, and other clients may takeover if download failed or that client terminates
- at the beginning of training games (after playMatch), all older networks that is not the current one is deleted
- allows client to sleep loop when playMatch error. This allows low gpu memory clients to only contribute to training games
Lockfile support using [github.com/nightlyone/lockfile](https://github.com/nightlyone/lockfile)
Only tested on Ubuntu.
Edit: tested on Windows by @borg323
=> Add lockfile support

lc0_main.go
This removes the currently non-working debug option for the time being. To make it useful it looks like lc0 changes are needed. The `lc0 is never quiet.` messages are also removed, as the joke has worn thin.
=> remove non-working debug option

lc0_main.go
Currently selfplay stops before downloading the nets for the next match. Downloading a net takes a bit more than 30 sec for me, and with a new net every 30 minutes, this adds up. This patch prefetches the candidate net before terminating selfplay and starting the match.
=> prefetch next net before terminating game

lc0_main.go
This pr does several things:
1. Checks that lc0 runs early, before downloading anything
2. If no --backend-opts are given, and cudnn is available, cudnn-fp16 is tried first and if no parallelism is given 32 is used with it.
3. If cudnn-fp16 is not available, the cudnn bckend is used immediately
4. the --gpu option can select gpu, but only if --backend-opts is not used.
=> Autodetect cudnn-fp16 and re-enable --gpu option

lc0_main.go
Datadir deletion didn't work because strings are passed by value in capture and are immutable.  Creating a shared slice of length 1 allows for a common object that can be mutated to show the new string value.
=> Fix cleanup of datadirs

lc0_main.go, src/client/client_http.go
With this the client gets KeepTime from the server (initially was the `-keep-time=xxx` option), to only delete networks older than the specified time. This is in addition to the `-keep` option. 
The default is to not delete nets received in the last 4 hours if no KeepTime is received and `-keep` is not given. This should be enough for clients serving two runs in the same directory even if a couple of nets fail to promote.
=> Get KeepTime from the server 

lc0_main.go
To enable easy comparison with top (active) users on https://lczero.org/
Output example:
`2019/01/31 10:58:19 lc0_main.go:166: Completed 77 games in 8m18.227504604s time (13352 games/day)
`
Comparing to https://lczero.org/
=> log #games/day

lc0_main.go
It was a bad idea to have the client use the "networks" directory - lc0 also searches in it by default and running the client in the same directory (where our pre-compiled windows packages have it) will:
1. Delete all networks there, even if they were downloaded by the user.
2. Get a new network, that lc0 will now use as default since it is newer.
=> rename networks directory

lc0_main.go
This adds a new flag, `-stats` (default off) to control whether to send additional info to the server. If set it sends the hostname, GPU name (only if `-backend-opts` is not used) and GPU number (from `-gpu`) to the server.
=> optionally send hostname and gpu info to server

lc0_main.go
For now, the dx backend is only run in 32 bit mode through the check backend so that 1% of its output can be verified using blas. We can probably get away with an even lower check rate, but 1% seemed like a good starting value.
=> be careful with the dx backend

lc0_main.go
1. Before starting, runs the equivalent of the check_dx script to guard against driver errors.
2. Keeps the continuous checks, but reduces the check frequency to 1e-5 (about 1 check every 50 games)
3. Stops setting the `-train-only` flag by default.
=> Updates for the dx backend

lc0_main.go
This was an idea by @mooskagh to make the client look a bit less suspicious to virus scanners.
=> execute lc0.exe in windows

lc0_main.go
With this, `settings.json` is renamed to `lc0-training-client-config.json` and is stored in `$XDG_CONFIG_HOME` or `$HOME/.config` in linux or `$HOME//Library/Preferences` in macos. The current directory is used under windows or if the environment variables are not defined.
The `-config` option is added to override the default file and location.
=> option and default directory for config file

lc0_main.go
It is very easy to mistakenly specify a cache directory that has important files in it.
=> make subdirectories in user specified cache directory

lc0_main.go
Also simplifies fp16 handling and adds a `-cudnn` boolean flag to disable the cudnn lc0 backend.
=> Support for cuda lc0 backend

client.sh
Simple script to download the client, build lc0 and start training. Tries to update both when the client complains or there is a crash. The update logic is:
- Always get the latest client.
- If the client signals an update alternate between latest rc and non-rc lc0 tags.
- If there is a crash and is not the first pass alternate between the last two non-rc lc0 tags.
=> linux autoupdate script

appveyor.yml, lc0_main.go
This might work on NFSv4 across multiple machines for cluster users. The old one relied upon checking pid out of file contents and assuming if it couldn't find PID the lock was stale.
However its unclear if this library will work on mac.  Will need testing.
=> Change to a different locking library that uses actual flock
